name: middleman

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Read .ruby-version
      id: ruby-version
      run: cat .ruby-version
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
        # ruby-version: ${{ steps.ruby-version.outputs.value }}
      
    - name: Install dependencies
      run: bundle install
    
    - name: Build application
      run: bundle exec middleman build
