name: middleman

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Read .ruby-version
      id: ruby-version
      run: | 
        echo ::set-env name=VERSION::$(cat .ruby-version)

    - name: test
      run: echo $VERSION
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
      
    - name: Install dependencies
      run: bundle install
    
    - name: Build application
      run: bundle exec middleman build
      
    - name: Archive build folder
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
