name: build-and-package
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: ruby/setup-ruby@v1.115.3
        with:
          bundler-cache: true
        
      - run: bundle exec middleman build
      
      - run: tar -czvf build.tar.gz build README.md LICENSE
      
#       - uses: actions/upload-artifact@v3
#         with:
#           name: build-$(date +%Y%m%d-%H%M%S)
#           path: build.tar.gz
          
      - uses: svenstaro/upload-release-action@v2
        with:
          file: build.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
