name: build-and-package
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: ruby/setup-ruby@v1.115.3
        with:
          bundler-cache: true
        
      - run: bundle exec middleman build
      
      - run: tar -czvf build-$(date +%Y%m%d-%H%M%S).tar.gz build
      
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: build-*.tar.gz
