name: build-and-package
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: ruby/setup-ruby@v1.115.3
        with:
          bundler-cache: true
        
      - run: bundle exec middleman build
      
      - run: tar -czvf build.tar.gz build README.md LICENSE
      - run: sha512sum build.tar.gz > checksum.sha512
          
      - uses: svenstaro/upload-release-action@v2
        with:
          file: build.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          
      - uses: svenstaro/upload-release-action@v2
        with:
          file: checksum
          tag: ${{ github.ref }}
          overwrite: true
